### ISSUE TITLE
Suggestion - regarding to "Add files to playlist" command

### ISSUE THREAD

**Issue by nagysifa** [mx3L/mediaplayer2#1]
What version of the product are you using? On what operating system?
- mp2 v0.60 + subssupport v1.5.3
- PBnigma 5.0.0 ( kernel 3.1.1 ) on VU+ UNO

Could You implement the folowing functions :
1. Start the "x" video file from the playlist after using the "Add files to playlist" ( where "x" is the file that the cursor was on when we selected the "Add files to playlist" command in the filelist.
( in present versions after the "Add files to playlist" command is used we must manually change from file list to playlist and manually start the video file that we want to play
1. When I start MP2, it starts in my "movies" folder. In it I have multiple directoryes like :

Cartoons
Horror
Drama
.
.
.

When I change directory to ( for example ) "Horror", then I get listed the video files from that dir, and the cursor is on "<Parent directrory>". If I use the "Add files to playlist" command, all my files from my "movies" folder will be added to the playlist not just the files from "Horror". ( and this is a bit confusing - this is what I'am asking You to change )
But if I move the cursor to down to the first or any movie in the filelist and use the "Add files to playlist" then only the files from my "Horror" folder will be added to the playlist.

Could You change this behavior ? ( This is not a new "behavior", it worked like this in the previous versions too - I'm just asking :) )

Once a gain theese are NOT errors! The player works flawlessly!

Thanx for your time and effort in advance!

**Comment by mx3L** [comment]
1) Problem is that if somebody wants to create their playlist from more directories or files. Everytime they would have to stop playback or at least open filelist again to add new files/directories to playlist.

Maybe I could add some option like "Add to playlist and play"? or assign some button which will start to play first item in playlist, not matter if you're in playlist of filelist.

2) When you enter directory, first entry is representing parent directory, so you have option to "Add directory in playlist" not "Add files to playlist", "Add files to playlist" is available only when you point to file. So this is correct behaviour. 

Maybe I could add some warning when you try to add parent directory to playlist

**Comment by nagysifa** [comment]
1) The  "Add to playlist and play" would be great!
2) Understood.

Thx

**Comment by mx3L** [comment]
1) How should this option behave when you have already created playlist and you're playing?

Suggestions when playing:
1. add entries after this playlist without playing since it's already playing
2. add entries after this playlist and play from first new added entry
Suggestions when not playing:
1. add entries after this playlist and play from first entry in playlist
2. add entries after this playlist and play from first new added entry

Or maybe better use case would be to clean playlist, create new playlist from entries and play, but name of the command should be then different.

What do you think? Any suggestions?

**Comment by nagysifa** [comment]
To bee honest, I newer use it that way, so I did not think over theese options ...
I would like this option for a clean playlist, but in case there is something in the playlist, using the option "Add to playlist and play" should clean the old playlist and add the new files. ( that is how I would like to use it ). But youre right that then the name sholud be " Add to clean playlist and play"

Since I would not use this option on a non-empty playlist, its make no difference to me, but if you need a vote :
Suggestions when playing:
1. add entries after this playlist without playing since it's already playing
Suggestions when not playing:
1. add entries after this playlist and play from first entry in playlist

**Comment by mx3L** [comment]
I guess there is no harm in adding it will add 1.suggestions..
