### ISSUE TITLE
mkv file with vobsub subtitles

### ISSUE THREAD

**Issue by fordfrog** [mx3L/mediaplayer2#4]
hi, i searched for info whether mp2 with subssupport displays subtitles from mkv files that have embedded vobsub subtitles. i just installed enigma2-plugin-extensions-subssupport_1.5.4_20150824_all.ipk and enigma2-plugin-extensions-mediaplayer2_0.61_20150909_all.ipk on my vu+ zero which has vti image installed. i tried to play an mkv file with vobsub subtitles but the player/subssuport does not see the subtitles. the mkv file works fine in vlc for example including the embedded vobsub subtitles.

so my question is, does mp2 with subssupport support mkv files with vobsub subtitles?

**Comment by mx3L** [comment]
Hi, vobsub is not supported, only text based subtitles are directly supported(srt, sub) by subssupport plugin.

Subtitles embedded in containers are supported directly by enigma2, but unfortunately vobsub support is not implemented yet.
http://forums.openpli.org/topic/38222-vob-subtitles-not-working/?hl=vobsub#entry495402

**Comment by fordfrog** [comment]
ok, thank you very much for your answer, looks like i should convert the subtitles :-)
