### ISSUE TITLE
Request - Rename plugin in Main menu

### ISSUE THREAD

**Issue by nunigaia** [mx3L/mediaplayer2#5]
Hi mx3L,

Hope you are fine.

Is there any possible to rename in Mediaplayer2 plugin rename the "Mediaplayer" main menu name for Mediaplayer 2, to avoid confusion with "Mediaplayer" in the next releases. 
In this case, i suggest to modify, but don´t know, i´m not sure, that technicaly if this it is the only necessary modification.

Original plugin.py file lines 1367 to 1370.

def menu(menuid, **kwargs):
    if menuid == "mainmenu" and config.plugins.mediaplayer2.mainMenu.getValue():
        return [(_("Media player"), main, "media_player2", 44)]
    return []

Mofication suggestion:

def menu(menuid, **kwargs):
    if menuid == "mainmenu" and config.plugins.mediaplayer2.mainMenu.getValue():
        return [(_("Media player 2"), main, "media_player2", 44)]
    return [] 

thanks in advance.
best regards
nunigaia

**Comment by ghost** [comment]
I think it's fine as it is now. You should remove standard Media Player before installing this. No need to use both.

**Comment by nunigaia** [comment]
Tony

In Blackhole images, or any other if you listen ( play media audio files throw Xbmc ) there´s no audio with Mediaplayer2. In this case you need the 2 plugins ... Mediaplayer classic and Mediaplayer2.

I don´t have problems, cause i have made the modifications mentioned on my previous post.

**Comment by ghost** [comment]
Ooh, right. That can lead to some confusion...
But for me that is already a mess,  Media Player + Xbmc + MediaPlayer2.
Glad I'm fine with just one ;)

**Comment by mx3L** [comment]
@nunigaia

I didn't renamed it because it would look ugly :), and I suppose there is no need to install more than one mediaplayer.

mediaplayer2 is just backend, it has to behave same as in mediaplayer, as long as you provide same url.

**Comment by nunigaia** [comment]
@mx3L 

No problem ... thanks for your reply and explanation. During the conversation you have with me in Vu community forum, have you made some progress, with handling audio via XBMC? 

best regards
nunigaia

**Comment by mx3L** [comment]
No I did not, however I've made some improvements in xbmc(kodi), and created specific player just for this purpose. Hopefully it will be finished soon..

**Comment by nunigaia** [comment]
Nice ... If you need a beta tester, don´t hesitate contact me, you know how to find me.

best regards
